### ISSUE TITLE
Default step

### ISSUE THREAD

**Issue by GeorgeKagan** [madoar/ng2-archwizard#19] opened 2017-07-17 15:06 UTC
Hi,

Is there a way to easily set the default step to be selected upon page load?
I would like to not have to click through steps to get to the one I'm currently developing.

I think it could be a nice development feature (disregarding step validation could make it easier I guess)!

Example (selected attribute):
<wizard-step data-title="General" navigationSymbol="1" **selected**></wizard-step>

Thanks

**Comment by madoar** [comment] 2017-07-18 19:42
Currently there is no way to select another than the first step as the default step of the wizard.
The problem is, that the the wizard requires all previous steps to be completed before it can enter a later step. This doesn't directly affect the selection of the default step, but the navigation from inside this step.

Let's say for example, that you take the second step as the default step, i.e. the step the wizard is inside when you visit the page. In this case you wouldn't be able to leave it in forward direction, because the previous (first) step hasn't been completed yet.
Allow this is part of issue #7.

Apart from that I like your suggestion of setting the default step by adding a directive (`selected`) to the default wizard step. I think I'll add this directive when working on #7.
Currently I'm quite low on time and therefore can't work on this at the moment, which is also the reason for my late answer.

**Comment by lexcaraig** [comment] 2017-09-13 23:26
Any update on this? Thanks!

**Comment by madoar** [comment] 2017-09-14 17:02
I've just opened a new branch and a PR for the required changes. 
But I'll need to write a few more tests for this and I'm also thinking about maybe changing/improving the variable names.
If you can live with this feel free to test my branch https://github.com/madoar/ng2-archwizard/tree/add-default-step-selection.
If you find anything you think can be improved don't hesitate to add a comment here.

**Comment by madoar** [comment] 2017-09-16 20:39
Ok, I've just merged #37 into the master branch. Which means, that it's now possible to select a different default step, than the first one.
For more details about how to do this, please take look at the `README` file.
Please be aware, that it will still take a while until I do the next release of `ng2-archwizard`, because I first want to work on some additional issues.

**Closed by madoar** 2017-09-16 20:39 UTC
Labels: feature request
