### ISSUE TITLE
Hide/show an optional step

### ISSUE THREAD

**Issue by asalhani** [madoar/ng2-archwizard#75] opened 2017-12-10 19:35 UTC
@madoar 
I need your kind support to show me how I can hide/show an optional step using typescript.
I went through your code, I discovered that there is a [hidden()] function in wizard-step.interface.ts
([](https://github.com/madoar/ng2-archwizard/blob/4f8c2a319627d24617ae8681d78159c69dbecaec/src/components/util/wizard-step.interface.ts))
However, it only allow get, therefore, I can't set the step hidden proparty.

thank you

**Comment by madoar** [comment] 2017-12-12 16:18
What do you mean by "hide/show"? 
The `hidden` field inside `wizard-step.interface.ts` is used to mark the current selected step of the wizard and is therefore not exposed to outside components.

**Comment by asalhani** [comment] 2017-12-13 06:46
@madoar 
what I meant with Hide/show is like the below senario:
Suppose I have a wizard with 5 steps. However, the 3rd step is optional and will be decided dynamically by user selection in step 1. 
What I want is:  Initially, when the wizard loaded for 1st time, I want to configure wizard such as the 3rd step is hidden. However, when the user select a property in step 1, then the 3rd step should be shown.

I hope my explanation was clear this time

**Comment by furqanaziz** [comment] 2017-12-18 18:50
@asalhani Simply put *ngIf on the <wizard-step> you want to show/hide based on some user input from step 1.

**Comment by madoar** [comment] 2017-12-20 14:03
It should work exactly like @furqanaziz wrote. 
You just need to make sure that the user is only able to change the visibility of later steps than the one he is currently inside, otherwise the wizard will have a problem with its current internal state.

**Comment by patriceo** [comment] 2018-01-09 13:53
Hi there ! First thanks for this nice component.

I'm trying to implement the same behaviour with step disabled when not applicable (depending on a REST api call), so I implemented a similar solution using a kind of:

`<wizard navBarLayout="large-empty-symbols">
        <wizard-step title="My Step 1" *ngIf="step1Available" navigationSymbolFontFamily="FontAwesome" navigationSymbol="&#xff19d;">
          <div class="wizard-step-container">
           ... children components
          </div>
        </wizard-step>
...
</wizard>`

This is working great, except in logs angular is complaining about it:

```
SimulationWizardComponent.html:13 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.
    at viewDebugError (core.es5.js:8433) [angular]
    at expressionChangedAfterItHasBeenCheckedError (core.es5.js:8411) [angular]
    at checkBindingNoChanges (core.es5.js:8575) [angular]
    at checkNoChangesNodeInline (core.es5.js:12416) [angular]
    at checkNoChangesNode (core.es5.js:12390) [angular]
    at debugCheckNoChangesNode (core.es5.js:13183) [angular]

```

I'm not sure where it comes from **step1Available** is only assigned in a Subscribe() of an observable and not binded to children components.

Any idea ?

**Comment by furqanaziz** [comment] 2018-01-09 18:17
@patriceo Please try putting `?` after the `*ngIf` variable, I am in a hurry and will share the details later:

```
<wizard navBarLayout="large-empty-symbols">
        <wizard-step title="My Step 1" *ngIf="step1Available?" navigationSymbolFontFamily="FontAwesome" navigationSymbol="&#xff19d;">
```

**Comment by patriceo** [comment] 2018-01-11 22:29
Hi @furqanaziz I managed to fixed it, but my fix is not that simple. I injected the ChangeDetectorRef in my component constructor and I called detach() before manipulating my variables then reattach() / detectChanges() right after.

However I will try your proposal !

**Comment by myspivey** [comment] 2018-01-15 18:45
I am having an issue where using *ngIf causes the steps to no longer function and transition between each properly. The second step ends up getting stuck if I hide the first step based off a variable. I noticed in the latest that there is no way to reset or rebuild the wizard programmatically either.

**Comment by furqanaziz** [comment] 2018-01-15 20:40
@myspivey do you mind sharing plunker or your code a bit, I thin there might be complex `canExit`/`canEnter` on second step possibly. You can hide first step / last step / any step with ngIf.

**Comment by myspivey** [comment] 2018-01-15 20:43
Sadly I can not but will try to get something together. Having said that, I do not have any canExit or Enter setup, it is using navigationMode="free" and that is all. It strikes me the issue is that if I hide the step after creation, instead of moving to the next step the component is staying on that first step even though it is no longer technically part of the process.

**Comment by asalhani** [comment] 2018-01-16 08:40
Sorry for late follow up. I tried to apply the solution proposed earlier by @furqanaziz and @madoar, however it didn't worked. So what I did is I set the step to be optional then I rendered it inside <div>. After that I putted *ngIf on the div. This way I'm contrlling the visibility of <div> NOT steps.

Although this is worked for me, I highly encourage @madoar  to consider making this as configuration on the step to make our life (dev :) easier.

**Comment by madoar** [comment] 2018-01-16 20:30
Ok, it's possible that I now know where the error is located.
The problem could be located in the way the wizard steps are internally managed.
Currently the wizard creates a model object at startup. 
This model contains an array representation of the steps instead of the initial `QueryList`.
I don't think this array is updated automatically by angular, which can result in the problem, that changes to the DOM aren't fully known to the model.

To solve the problem once and for all, it should suffice to add a listener to the `QueryList` that detects changes inside the list and then automatically updates internal model of the wizard.

**Closed** 2018-01-28 14:22 UTC
Labels: question

**Comment by candorthor** [comment] 2019-04-02 07:19
@madoar 
I need a help on solving the issue. I have a wizard, where I made step 3 and step 5 as optional step. When I click the "Next Step" button in step 1, I want step 2 and step 4 to be hidden  and step 3 and step 4 to be displayed. I have used *ngIf. The problem is when clicked on "Next Step" button of step 1, wizard circle is working as expected, but the contents of the step 3 (i.e "Go to previous step" button and "Go to next step" button) are not displaying.  Below is the code.


.html file

<wizard>
  <wizard-step stepTitle="Title of step 1" [canExit]='true'>
    Content of Step 1
    <button type="button" nextStep (click)="optional()">Next Step</button>
  </wizard-step>
  <wizard-step stepTitle="Title of step 2" *ngIf="optionStep === 'no'" ></wizard-step>
  <wizard-step stepTitle="Title of step 3" *ngIf="optionStep === 'yes'" optionalStep>
    Content of Step 2
    <button type="button" previousStep>Go to previous step</button>
    <button type="button" nextStep>Go to next step</button>
  </wizard-step>
  <wizard-step stepTitle="Title of step 4"  *ngIf="optionStep === 'no'"></wizard-step>
  <wizard-step stepTitle="Title of step 5" *ngIf="optionStep === 'yes'" optionalStep>
    Content of Step 3
    <button type="button" previousStep>Previous Step</button>
    <button type="button">Finish</button>
  </wizard-step>
</wizard>


.ts file
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  optionStep: any;
  name = 'Angular 5';

  constructor() {
        this.optionStep = 'no'
    }

 optional() {
        this.optionStep = 'yes'

    }
}

**Comment by candorthor** [comment] 2019-04-04 06:57
@madoar 

Can anyone look into this please?

**Comment by madoar** [comment] 2019-04-04 19:26
@candorthor your question here is a duplicate of #201, right?
Please open a new issue for new questions. This makes it much easier for me to track this.
For an answer to your question please take a look at #201.
